# NumPy Library

Lits are slow. NumPy are very fast.  
Numpy has relatively low number of bits.(Faster to read less bytes of memory.)   
No type checking when iterating through objects.


Lists - Insertion, Deletion, Appending, Concatenation etc.    
NumPy - Insertion, Deletion, Appending, Concatenation etc. + Lots more


Import the NumPy module:

In [1]:
import numpy as np

Create a List and a NumPy

In [3]:
a = [1,3,5]
b = [1,2,3] #list

c = np.array([1,3,5])
d = np.array([1,2,3]) #numpy

We can multiply 2 numpy arrays.  
a * b = Error  
c * d = Okay

In [6]:
print(c*d)

[ 1  6 15]


#### Applications of NumPy  

Mathematics (MATLAB)            
Plotting (Matplotlib)                             
Backend (Pandas, Connect 4, Digital Photography)                   
Machine Learning               

In [13]:
#Two dimentional array.
e = np.array([[0.2,1.5,0.8],[1.2,0.7,1],[0.1,1.3,0.5]]) 

print(e)

[[0.2 1.5 0.8]
 [1.2 0.7 1. ]
 [0.1 1.3 0.5]]


In [8]:
#Three dimentional array.
f = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) 

print(f)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


How we get the dimention, shape and data type of a array?

In [10]:
#Get Dimention
print(f.ndim)

3


In [12]:
#Get Shape
print(d.shape)
print(e.shape)
print(f.shape)

(3,)
(3, 3)
(2, 2, 2)


In [14]:
#Get Data Type
print(d.dtype)
print(e.dtype)
print(f.dtype)

int32
float64
int32


We can set the data type and size for an array manually.   
Defalt size of a integer is 32 bits.  
Defalt size of a float is 64 bits.   
But we can change it.

In [22]:
g = np.array([[1,2,5],[3,6,4]] , dtype = 'int16')

print(g.dtype)

int16


In [25]:
# Get item size in bytes

print(g.itemsize)

2


## Accessing/ changing specific elements, rows, columns, etc.

In [30]:
a = np.array([[2,5,8,7,4,6,1],[8,6,2,3,6,9,4]])
print(a)

[[2 5 8 7 4 6 1]
 [8 6 2 3 6 9 4]]


In [31]:
# Get a specific element [row,column]
a[1,-2]

9

In [32]:
# Get a specific row
a[0,:]

array([2, 5, 8, 7, 4, 6, 1])

In [34]:
# Get a specific column
a[:,3]

array([7, 3])

In [39]:
# Getting a range [StartIndex : EndIndex : StepSize]
print(  a[1,2:-1]  )
print(  a[0,0:-2:2]  )

[2 3 6 9]
[2 8 4]


In [40]:
# Assign a element
a[1,4] = 77

a

array([[ 2,  5,  8,  7,  4,  6,  1],
       [ 8,  6,  2,  3, 77,  9,  4]])

3D Example

In [41]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) 

print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [42]:
# Get specific element ( Layer , Row , Column)
b[1,0,1]

6

In [45]:
b[:,:,1]

array([[2, 4],
       [6, 8]])

In [46]:
b[:,:,1] = [[12,45],[23,15]] #Replace a part of array
b

array([[[ 1, 12],
        [ 3, 45]],

       [[ 5, 23],
        [ 7, 15]]])

## Initializing Different Types of Arrays

In [56]:
# All zeros matrix
np.zeros((5))

array([0., 0., 0., 0., 0.])

In [58]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [59]:
np.zeros((2,3,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [62]:
# All ones Matrix 
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [63]:
np.ones((3,4), dtype = 'int8')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [66]:
# Any other Numbers
np.full((2,2), 99, dtype = "float16")

array([[99., 99.],
       [99., 99.]], dtype=float16)

In [67]:
np.full(a.shape, 41)  

array([[41, 41, 41, 41, 41, 41, 41],
       [41, 41, 41, 41, 41, 41, 41]])

In [76]:
# Any other number ( full_like )
np.full_like(a,1)

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

## Random Numbers

In [69]:
np.random.rand(2,3,4)

array([[[0.81009706, 0.78402809, 0.65888975, 0.66205841],
        [0.42866212, 0.96072963, 0.2487124 , 0.06395815],
        [0.0658659 , 0.47046169, 0.42419809, 0.36523947]],

       [[0.24954213, 0.9755726 , 0.57513631, 0.61817011],
        [0.88294487, 0.18779316, 0.055669  , 0.34785316],
        [0.81250654, 0.72888604, 0.82960141, 0.24201203]]])

In [70]:
np.random.random_sample(a.shape)

array([[0.03781254, 0.05490485, 0.04023838, 0.02055337, 0.84032057,
        0.13877511, 0.04448558],
       [0.72934291, 0.99230086, 0.75253448, 0.50494953, 0.96560288,
        0.56976643, 0.01980667]])

In [74]:
# Random integer values
# np.random.randint(maximum value, size)

np.random.randint(4200, size =(2,2))

array([[ 594, 1033],
       [  81,  306]])

In [75]:
# np.random.randint(minimum value, maximum value, size)

np.random.randint(4,40, size =(3,3))

array([[25, 28,  7],
       [ 6, 11, 29],
       [31,  7, 12]])

In [77]:
# The identity matrix

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [91]:
# Repeat an array 
# np.repeat(array, x times, axis)
arr = np.array([[1,2,3]])

np.repeat(arr,3,axis = 0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [92]:
np.repeat(arr,3,axis = 1)

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

Exercise 01

In [101]:
output = np.ones((5,5), dtype = 'int16')
output[1:4,1:4] = np.zeros((3,3))
output[2,2] = 9
print(output)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [102]:
a = np.array([1,2,3])
b = a           # Let's asign a to b

b[1] = 100 # Let's change b

print('b = ',b)
print('a = ',a)

b =  [  1 100   3]
a =  [  1 100   3]


a also changed due to changing b. It is a problem

In [103]:
# We can use copy function to overcome this issue.

a = np.array([1,2,3])
b = a.copy()           # Let's asign a to b

b[1] = 100 # Let's change b

print('b = ',b)
print('a = ',a)

b =  [  1 100   3]
a =  [1 2 3]


## Mathematics

In [104]:
a = np.array([1, 5, 8, 3, 9, 7, 2, 4, 6 ])
b = np.array([45, 69, 12, 34, 28, 57, 19, 40, 58])

In [109]:
print(a + b)

[46 74 20 37 37 64 21 44 64]


In [110]:
print(a + 2)

[ 3  7 10  5 11  9  4  6  8]


In [111]:
print(a - 5)

[-4  0  3 -2  4  2 -3 -1  1]


In [112]:
print(a ** 2)

[ 1 25 64  9 81 49  4 16 36]


In [116]:
print( np.sin(b) )

[ 0.85090352 -0.11478481 -0.53657292  0.52908269  0.27090579  0.43616476
  0.14987721  0.74511316  0.99287265]


## Linear Algebra

In [125]:
a = np.random.randint(10,30, size = (2,3))
b = np.random.randint(30,50, size = (3,4))

print(a)
print(b)

[[14 16 19]
 [13 14 25]]
[[45 41 47 32]
 [36 44 38 35]
 [46 45 44 35]]


In [128]:
# Matrix Multiplication (np.matmul)

print(   np.matmul(a,b)    )

[[2080 2133 2102 1673]
 [2239 2274 2243 1781]]


In [136]:
# Determinant (np.linalg.det)
c = np.identity(3) * 3

print(   np.linalg.det(c)    )

27.0


In [137]:
# Matrix / Vector norm

print(   np.linalg.norm(a)   )

42.46174749112429


In [145]:
# Eigen Values
d = np.random.randint(9, size = (4,4))

print(d)
print(   np.linalg.eigvals(d)    )

[[6 2 0 5]
 [3 4 1 2]
 [1 8 1 4]
 [7 1 0 2]]
[11.53972505  4.45845178 -2.354197   -0.64397983]


#### More functions to linear algebra : https://numpy.org/doc/stable/reference/routines.linalg.html

## Statistics

In [147]:
stat = np.array([[2,8,7],[6,9,1]])
print(stat)

[[2 8 7]
 [6 9 1]]


In [152]:
np.min(stat)    # The minimum value in the array

1

In [153]:
np.min(stat, axis = 0)   # Lowest values in each column

array([2, 8, 1])

In [155]:
np.max(stat, axis = 1)

array([8, 9])

In [156]:
np.sum(stat, axis = 0)    # Sum of each column

array([ 8, 17,  8])

## Reorganizing Arrays

In [158]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print(before.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [159]:
# Reshape
before.reshape((1,8))

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [160]:
before.reshape((8,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [161]:
before.reshape((2,2,2))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [162]:
# Vertically stacking vectors (vstack)
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [164]:
# Horizontal stacking vectors (hstack)
h1 = np.array([1,2,3,4])
h2 = np.array([5,6,7,8])

np.hstack([h2,h1])

array([5, 6, 7, 8, 1, 2, 3, 4])

## Miscellaneous

#### Load data from file         
#### np.genfromtxt( file, delimeter =',')

In [178]:
filedata = np.genfromtxt("data.txt", delimiter=",")

filedata = filedata.astype('int32')

print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   2   1   9   8   7   1  76  88]]


#### Boolean masking and advance indexing

In [179]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [182]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [183]:
a = np.array([1,2,3,4,5,6,7,8,9])

# You can index with a list a NumPy
a[[1,4,7]]

array([2, 5, 8])

In [192]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [194]:
b[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [195]:
b[[0,4,5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

#### Boolean

In [184]:
np.any(filedata>50 , axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [185]:
np.all(filedata>50 , axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [187]:
np.any(filedata>50 , axis=1)

array([ True,  True,  True])

In [188]:
np.all(filedata>50 , axis=1)

array([False, False, False])

In [190]:
((filedata>50) & (filedata<100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [191]:
(~((filedata>50) & (filedata<100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])